nuxeo/nuxeo-platform-forms-layout-demo

- ftest/webdriver/src/main/java/org/nuxeo/functionaltests/formsLayoutDemo/page/standardWidgets/ListStandardWidgetPage.java
- ftest/webdriver/src/test/java/org/nuxeo/ftest/formsLayoutDemo/ITJSListWidgetTest.java
- nuxeo-platform-forms-layout-demo/src/main/resources/OSGI-INF/demo/layout-demo-complex-list-widget.xml
- nuxeo-platform-forms-layout-demo/src/main/resources/OSGI-INF/demo/layout-demo-complex-list2-widget.xml
- nuxeo-platform-forms-layout-demo/src/main/resources/OSGI-INF/demo/layout-demo-list-array-widget.xml
- nuxeo-platform-forms-layout-demo/src/main/resources/OSGI-INF/demo/layout-demo-list-widget.xml
- nuxeo-platform-forms-layout-demo/src/main/resources/OSGI-INF/demo/layout-demo-listOfLists-widget.xml
- nuxeo-platform-forms-layout-demo/src/main/resources/web/nuxeo.war/layoutDemo/widget_demo.xhtml
PR created from https://qa.nuxeo.org/jenkins/job/ondemand-testandpush-ajusto-7.10/6/
> fix-NXP-19534-list-widget-7.10

- ftest/webdriver/src/test/java/org/nuxeo/ftest/formsLayoutDemo/AbstractWidgetPageTest.java
- ftest/webdriver/src/test/java/org/nuxeo/ftest/formsLayoutDemo/ITActionsWidgetTest.java
- ftest/webdriver/src/test/java/org/nuxeo/ftest/formsLayoutDemo/ITMenuTest.java
- ftest/webdriver/src/test/java/org/nuxeo/ftest/formsLayoutDemo/ITToggleableLayoutWidgetTest.java
PR created from https://qa2.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-atchertchian-8.10/5/
> fix-NXP-21489-NXP-21238-layout-demo-webdriver-randoms-8.10

- ftest/webdriver/src/test/java/org/nuxeo/ftest/formsLayoutDemo/ITAjaxListWidgetTest.java
- ftest/webdriver/src/test/java/org/nuxeo/ftest/formsLayoutDemo/ITComplexWidgetTest.java
- ftest/webdriver/src/test/java/org/nuxeo/ftest/formsLayoutDemo/ITIntWidgetTest.java
- ftest/webdriver/src/test/java/org/nuxeo/ftest/formsLayoutDemo/ITJSListWidgetTest.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-troger/66/
> fix-NXP-21815-int-widget

- ftest/webdriver/src/test/java/org/nuxeo/ftest/formsLayoutDemo/ITAjaxListWidgetTest.java
- ftest/webdriver/src/test/java/org/nuxeo/ftest/formsLayoutDemo/ITComplexWidgetTest.java
- ftest/webdriver/src/test/java/org/nuxeo/ftest/formsLayoutDemo/ITIntWidgetTest.java
- ftest/webdriver/src/test/java/org/nuxeo/ftest/formsLayoutDemo/ITJSListWidgetTest.java
PR created from https://qa2.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-troger-8.10/33/
> 8.10-HF/fix-NXP-21815-int-widget

- ftest/webdriver/src/test/java/org/nuxeo/ftest/formsLayoutDemo/ITActionsWidgetTest.java
PR created from https://qa2.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-atchertchian-7.10/51/
> fix-NXP-23003-adapt-webdriver-tests-optims

- nuxeo-platform-forms-layout-demo/src/main/java/org/nuxeo/ecm/platform/forms/layout/demo/jsf/LayoutDemoContext.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume/311/
> cleanup-NXP-24089-CloseableCoreSession

- ftest/webdriver/src/test/java/org/nuxeo/ftest/formsLayoutDemo/ITMenuTest.java
- nuxeo-platform-forms-layout-demo/pom.xml
- nuxeo-platform-forms-layout-demo/src/main/java/org/nuxeo/ecm/platform/forms/layout/demo/jsf/LayoutDemoURLCodec.java
- nuxeo-platform-forms-layout-demo/src/main/java/org/nuxeo/ecm/platform/forms/layout/demo/jsf/LayoutPreviewActions.java
- nuxeo-platform-forms-layout-demo/src/main/java/org/nuxeo/ecm/platform/forms/layout/demo/jsf/PreviewLayoutDefinition.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-kleturc/356/
> cleanup-NXP-24090-replace-commons-lang-with-lang3

- ftest/webdriver/src/main/java/org/nuxeo/functionaltests/formsLayoutDemo/page/ValidationPage.java
- ftest/webdriver/src/test/java/org/nuxeo/ftest/formsLayoutDemo/ITLayoutDocumentValidationTest.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fdavid-master/327/
> fix-NXP-23644-add-webdriver-test-for-reproduction

- nuxeo-platform-forms-layout-demo/src/main/java/org/nuxeo/ecm/platform/forms/layout/demo/service/DemoWidgetTypeImpl.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-fguillaume/318/
> cleanup-NXP-24092-code-quality-3

- ftest/webdriver/src/test/java/org/nuxeo/ftest/formsLayoutDemo/ITAjaxListWidgetTest.java
- ftest/webdriver/src/test/java/org/nuxeo/ftest/formsLayoutDemo/ITComplexWidgetTest.java
- ftest/webdriver/src/test/java/org/nuxeo/ftest/formsLayoutDemo/ITJSListWidgetTest.java
- nuxeo-platform-forms-layout-demo/src/main/resources/schemas/layout_demo_schema.xsd
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-troger/201/
> fix-NXP-23908-default-value-js-list

- ftest/webdriver/src/test/java/org/nuxeo/ftest/formsLayoutDemo/ITAjaxListWidgetTest.java
- ftest/webdriver/src/test/java/org/nuxeo/ftest/formsLayoutDemo/ITComplexWidgetTest.java
- ftest/webdriver/src/test/java/org/nuxeo/ftest/formsLayoutDemo/ITJSListWidgetTest.java
- nuxeo-platform-forms-layout-demo/src/main/resources/schemas/layout_demo_schema.xsd
PR created from https://qa2.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-troger-8.10/86/
> 8.10-HF/fix-NXP-23908-default-value-js-list

- ftest/webdriver/src/test/java/org/nuxeo/ftest/formsLayoutDemo/ITAjaxListWidgetTest.java
- ftest/webdriver/src/test/java/org/nuxeo/ftest/formsLayoutDemo/ITComplexWidgetTest.java
- ftest/webdriver/src/test/java/org/nuxeo/ftest/formsLayoutDemo/ITJSListWidgetTest.java
- nuxeo-platform-forms-layout-demo/src/main/resources/schemas/layout_demo_schema.xsd
PR created from https://qa2.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-troger-7.10/42/
> 7.10-HF/fix-NXP-23908-default-value-js-list

- ftest/webdriver/src/test/java/org/nuxeo/ftest/formsLayoutDemo/ITAjaxListWidgetTest.java
- ftest/webdriver/src/test/java/org/nuxeo/ftest/formsLayoutDemo/ITComplexWidgetTest.java
- ftest/webdriver/src/test/java/org/nuxeo/ftest/formsLayoutDemo/ITJSListWidgetTest.java
- nuxeo-platform-forms-layout-demo/src/main/resources/schemas/layout_demo_schema.xsd
PR created from https://qa2.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-troger-9.10/3/
> 9.10-HF/fix-NXP-23908-default-value-js-list

- ftest/webdriver/src/test/java/org/nuxeo/ftest/formsLayoutDemo/ITAjaxListWidgetTest.java
- ftest/webdriver/src/test/java/org/nuxeo/ftest/formsLayoutDemo/ITJSListWidgetTest.java
- ftest/webdriver/src/test/java/org/nuxeo/ftest/formsLayoutDemo/ITToggleableLayoutWidgetTest.java
PR created from https://qa2.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-atchertchian-8.10/32/
> fix-NXP-22345-seletct2-cache-jsf-listing-8.10

- ftest/webdriver/src/test/java/org/nuxeo/ftest/formsLayoutDemo/ITAjaxListWidgetTest.java
- ftest/webdriver/src/test/java/org/nuxeo/ftest/formsLayoutDemo/ITJSListWidgetTest.java
- ftest/webdriver/src/test/java/org/nuxeo/ftest/formsLayoutDemo/ITToggleableLayoutWidgetTest.java
PR created from https://qa2.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-atchertchian-7.10/60/
> fix-NXP-22345-seletct2-cache-jsf-listing-7.10

- ftest/webdriver/src/test/java/org/nuxeo/ftest/formsLayoutDemo/ITAjaxListWidgetTest.java
- ftest/webdriver/src/test/java/org/nuxeo/ftest/formsLayoutDemo/ITJSListWidgetTest.java
- ftest/webdriver/src/test/java/org/nuxeo/ftest/formsLayoutDemo/ITToggleableLayoutWidgetTest.java
PR created from https://qa2.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-atchertchian-9.10/4/
> fix-NXP-22345-seletct2-cache-jsf-listing-9.10

- ftest/webdriver/src/test/java/org/nuxeo/ftest/formsLayoutDemo/ITFileWidgetTest.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-atchertchian-master-2/69/
> fix-NXP-21468-jsf-file-upload-keep-master

- ftest/webdriver/src/test/java/org/nuxeo/ftest/formsLayoutDemo/ITAjaxListWidgetTest.java
- ftest/webdriver/src/test/java/org/nuxeo/ftest/formsLayoutDemo/ITComplexWidgetTest.java
- ftest/webdriver/src/test/java/org/nuxeo/ftest/formsLayoutDemo/ITIntWidgetTest.java
- ftest/webdriver/src/test/java/org/nuxeo/ftest/formsLayoutDemo/ITJSListWidgetTest.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-troger/227/
> fix-NXP-24878-int-widget-max-value

- ftest/webdriver/src/test/java/org/nuxeo/ftest/formsLayoutDemo/ITAjaxListWidgetTest.java
- ftest/webdriver/src/test/java/org/nuxeo/ftest/formsLayoutDemo/ITComplexWidgetTest.java
- ftest/webdriver/src/test/java/org/nuxeo/ftest/formsLayoutDemo/ITIntWidgetTest.java
- ftest/webdriver/src/test/java/org/nuxeo/ftest/formsLayoutDemo/ITJSListWidgetTest.java
PR created from https://qa2.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-troger-9.10/20/
> 9.10-HF/fix-NXP-24878-int-widget-max-value

- ftest/webdriver/src/test/java/org/nuxeo/ftest/formsLayoutDemo/ITAjaxListWidgetTest.java
- ftest/webdriver/src/test/java/org/nuxeo/ftest/formsLayoutDemo/ITComplexWidgetTest.java
- ftest/webdriver/src/test/java/org/nuxeo/ftest/formsLayoutDemo/ITIntWidgetTest.java
- ftest/webdriver/src/test/java/org/nuxeo/ftest/formsLayoutDemo/ITJSListWidgetTest.java
PR created from https://qa2.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-troger-8.10/104/
> 8.10-HF/fix-NXP-24878-int-widget-max-value

- nuxeo-platform-forms-layout-demo/src/main/java/org/nuxeo/ecm/platform/forms/layout/demo/jsf/LayoutDemoContext.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-kleturc/535/
> fix-NXP-25983-replace-remaining-deleted-state

- ftest/webdriver/src/test/java/org/nuxeo/ftest/formsLayoutDemo/ITAggregateWidgetTest.java
- nuxeo-platform-forms-layout-demo/src/main/java/org/nuxeo/ecm/platform/forms/layout/demo/jsf/LayoutDemoActions.java
- nuxeo-platform-forms-layout-demo/src/main/java/org/nuxeo/ecm/platform/forms/layout/demo/jsf/LayoutDemoContext.java
- nuxeo-platform-forms-layout-demo/src/main/resources/META-INF/MANIFEST.MF
- nuxeo-platform-forms-layout-demo/src/main/resources/OSGI-INF/demo/layout-demo-agg-checkbox-user-widget.xml
- nuxeo-platform-forms-layout-demo/src/main/resources/OSGI-INF/demo/layout-demo-agg-listbox-user-widget.xml
- nuxeo-platform-forms-layout-demo/src/main/resources/OSGI-INF/deployment-fragment.xml
- nuxeo-platform-forms-layout-demo/src/main/resources/OSGI-INF/layout-demo-contrib.xml
- nuxeo-platform-forms-layout-demo/src/main/resources/schemas/layout_demo_schema.xsd
- nuxeo-platform-forms-layout-demo/src/main/resources/web/nuxeo.war/layoutDemo/demoWidgets/selectManyCheckboxUserAggregate.xhtml
- nuxeo-platform-forms-layout-demo/src/main/resources/web/nuxeo.war/layoutDemo/demoWidgets/selectManyListboxUserAggregate.xhtml
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-grenard-maven3/285/
> fix-NXP-26637-userGroupAggPrefix

- ftest/webdriver/src/test/java/org/nuxeo/ftest/formsLayoutDemo/ITAggregateWidgetTest.java
- nuxeo-platform-forms-layout-demo/src/main/java/org/nuxeo/ecm/platform/forms/layout/demo/jsf/LayoutDemoActions.java
- nuxeo-platform-forms-layout-demo/src/main/java/org/nuxeo/ecm/platform/forms/layout/demo/jsf/LayoutDemoContext.java
- nuxeo-platform-forms-layout-demo/src/main/resources/META-INF/MANIFEST.MF
- nuxeo-platform-forms-layout-demo/src/main/resources/OSGI-INF/demo/layout-demo-agg-checkbox-user-widget.xml
- nuxeo-platform-forms-layout-demo/src/main/resources/OSGI-INF/demo/layout-demo-agg-listbox-user-widget.xml
- nuxeo-platform-forms-layout-demo/src/main/resources/OSGI-INF/deployment-fragment.xml
- nuxeo-platform-forms-layout-demo/src/main/resources/OSGI-INF/layout-demo-contrib.xml
- nuxeo-platform-forms-layout-demo/src/main/resources/schemas/layout_demo_schema.xsd
- nuxeo-platform-forms-layout-demo/src/main/resources/web/nuxeo.war/layoutDemo/demoWidgets/selectManyCheckboxUserAggregate.xhtml
- nuxeo-platform-forms-layout-demo/src/main/resources/web/nuxeo.war/layoutDemo/demoWidgets/selectManyListboxUserAggregate.xhtml
PR created from https://qa2.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-atchertchian-8.10/42/
> fix-NXP-26637-userGroupAggPrefix-8.10

- ftest/webdriver/src/test/java/org/nuxeo/ftest/formsLayoutDemo/ITAggregateWidgetTest.java
- nuxeo-platform-forms-layout-demo/src/main/java/org/nuxeo/ecm/platform/forms/layout/demo/jsf/LayoutDemoActions.java
- nuxeo-platform-forms-layout-demo/src/main/java/org/nuxeo/ecm/platform/forms/layout/demo/jsf/LayoutDemoContext.java
- nuxeo-platform-forms-layout-demo/src/main/resources/META-INF/MANIFEST.MF
- nuxeo-platform-forms-layout-demo/src/main/resources/OSGI-INF/demo/layout-demo-agg-checkbox-user-widget.xml
- nuxeo-platform-forms-layout-demo/src/main/resources/OSGI-INF/demo/layout-demo-agg-listbox-user-widget.xml
- nuxeo-platform-forms-layout-demo/src/main/resources/OSGI-INF/deployment-fragment.xml
- nuxeo-platform-forms-layout-demo/src/main/resources/OSGI-INF/layout-demo-contrib.xml
- nuxeo-platform-forms-layout-demo/src/main/resources/schemas/layout_demo_schema.xsd
- nuxeo-platform-forms-layout-demo/src/main/resources/web/nuxeo.war/layoutDemo/demoWidgets/selectManyCheckboxUserAggregate.xhtml
- nuxeo-platform-forms-layout-demo/src/main/resources/web/nuxeo.war/layoutDemo/demoWidgets/selectManyListboxUserAggregate.xhtml
PR created from https://qa2.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-atchertchian-9.10/17/
> fix-NXP-26637-userGroupAggPrefix-9.10

- ftest/webdriver/src/test/java/org/nuxeo/ftest/formsLayoutDemo/ITAggregateWidgetTest.java
- nuxeo-platform-forms-layout-demo/src/main/java/org/nuxeo/ecm/platform/forms/layout/demo/jsf/LayoutDemoActions.java
- nuxeo-platform-forms-layout-demo/src/main/java/org/nuxeo/ecm/platform/forms/layout/demo/jsf/LayoutDemoContext.java
- nuxeo-platform-forms-layout-demo/src/main/resources/META-INF/MANIFEST.MF
- nuxeo-platform-forms-layout-demo/src/main/resources/OSGI-INF/demo/layout-demo-agg-checkbox-user-widget.xml
- nuxeo-platform-forms-layout-demo/src/main/resources/OSGI-INF/demo/layout-demo-agg-listbox-user-widget.xml
- nuxeo-platform-forms-layout-demo/src/main/resources/OSGI-INF/deployment-fragment.xml
- nuxeo-platform-forms-layout-demo/src/main/resources/OSGI-INF/layout-demo-contrib.xml
- nuxeo-platform-forms-layout-demo/src/main/resources/schemas/layout_demo_schema.xsd
- nuxeo-platform-forms-layout-demo/src/main/resources/web/nuxeo.war/layoutDemo/demoWidgets/selectManyCheckboxUserAggregate.xhtml
- nuxeo-platform-forms-layout-demo/src/main/resources/web/nuxeo.war/layoutDemo/demoWidgets/selectManyListboxUserAggregate.xhtml
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-grenard-maven3/287/
> fix-NXP-26637-userGroupAggPrefix-10.10

- ftest/webdriver/src/test/java/org/nuxeo/ftest/formsLayoutDemo/ITAjaxListWidgetTest.java
- ftest/webdriver/src/test/java/org/nuxeo/ftest/formsLayoutDemo/ITComplexWidgetTest.java
- ftest/webdriver/src/test/java/org/nuxeo/ftest/formsLayoutDemo/ITContainerWidgetTest.java
- ftest/webdriver/src/test/java/org/nuxeo/ftest/formsLayoutDemo/ITDatetimeWidgetTest.java
- ftest/webdriver/src/test/java/org/nuxeo/ftest/formsLayoutDemo/ITJSListWidgetTest.java
- ftest/webdriver/src/test/java/org/nuxeo/ftest/formsLayoutDemo/ITLayoutWidgetTest.java
- ftest/webdriver/src/test/java/org/nuxeo/ftest/formsLayoutDemo/ITToggleableLayoutWidgetTest.java
- nuxeo-platform-forms-layout-demo/src/main/java/org/nuxeo/ecm/platform/forms/layout/demo/jsf/LayoutDemoContext.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-kleturc-3/27/
> improvement-NXP-24952-compile-with-java11

- ftest/webdriver/src/test/java/org/nuxeo/ftest/formsLayoutDemo/ITAggregateWidgetTest.java
- nuxeo-platform-forms-layout-demo/src/main/java/org/nuxeo/ecm/platform/forms/layout/demo/jsf/LayoutDemoContext.java
PR created from https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-atchertchian-master/188/
> fix-NXP-27020-aggreg-user

- ftest/webdriver/src/test/java/org/nuxeo/ftest/formsLayoutDemo/ITAggregateWidgetTest.java
- nuxeo-platform-forms-layout-demo/src/main/java/org/nuxeo/ecm/platform/forms/layout/demo/jsf/LayoutDemoContext.java
PR created from https://qa2.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-atchertchian-9.10/19/
> fix-NXP-27020-aggreg-user-9.10

- ftest/webdriver/src/test/java/org/nuxeo/ftest/formsLayoutDemo/ITAggregateWidgetTest.java
- nuxeo-platform-forms-layout-demo/src/main/java/org/nuxeo/ecm/platform/forms/layout/demo/jsf/LayoutDemoContext.java
PR created from https://qa2.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-atchertchian-8.10/44/
> fix-NXP-27020-aggreg-user-8.10
